### PR TITLE
Update nltk_data package to HEAD of repo

### PR DESCRIPTION
**Pull request by kellend-git**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by kellend-git** [comment]
@conda-forge-admin, please rerender

**Review by danielfrg — APPROVED** [review]

**Comment by kellend-git** [comment]
@danielfrg can you merge? I don't have permissions

**Comment by kellend-git** [comment]
@benhuff @danielfrg @mxr-conda can one of you merge please?

**Comment by danielfrg** [comment]
thanks for the update!

**Pull request merged**
